solved
vladimir-arsenov/untitled3 pull request #1
Opened 2024-09-08 19:31 UTC by vladimir-arsenov

2024-09-08 19:39 UTC, margaret-collins requested changes
дои

2024-09-08 19:39 UTC, margaret-collins commented on src/Main.java
> -        System.out.printf("Hello and welcome!");
Здкесь должна быть пустая строка

2024-09-08 19:39 UTC, margaret-collins commented on src/Main.java
>  public class Main {
бьбьтбьтьбт

2024-09-09 08:13 UTC, margaret-collins requested changes

2024-09-09 08:13 UTC, margaret-collins commented on src/Main.java
>      public static void main(String[] args) {
add a couple of lines

2024-09-09 08:13 UTC, margaret-collins commented on src/Main.java
>  public class Main {
change signature and commetnts

2024-09-09 08:19 UTC, vladimir-arsenov commented on src/Main.java
>      public static void main(String[] args) {
bcghfdbk

2024-09-09 08:24 UTC, merged